=== jlheig/SER-LAB1/chess.dtd
<!-- ElÃ©ment racine -->
<!ELEMENT Association (AllPlayers, AllTeams, AllReferees, AllTournaments)>


<!-- Joueurs -->
<!ELEMENT AllPlayers (Player*)>
<!ELEMENT Player (Name, Surname, ELO)>
<!ATTLIST Player sid ID>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Surname (#PCDATA)>
<!ELEMENT ELO (#PCDATA)>

<!-- Equipes -->
<!ELEMENT AllTeams (Team*)>
<!ELEMENT Team (Name)>
<!ATTLIST Team id ID #REQUIRED player1 IDREF player2 IDREF>

<!ELEMENT Teams EMPTY>
<!ATTLIST Teams id IDREFS>

<!-- Arbitres -->
<!ELEMENT AllReferees (Referee*)>
<!ELEMENT Referee (Name, Surname)>
<!ATTLIST Referee id ID #REQUIRED>

<!ELEMENT Referees EMPTY>
<!ATTLIST Referees id IDREFS>

<!-- Tournois -->
<!ELEMENT AllTournaments (Tournament*)>
<!ELEMENT Tournament (Referees, Teams, Matchs)>
<!ATTLIST Tournament name CDATA winner IDREF>

<!-- Parties -->
<!ELEMENT Matchs (Match*)>
<!ELEMENT Match (Move*, Score+)>
<!ATTLIST Match date CDATA hour CDATA teamA IDREF teamB IDREF>
<!ELEMENT Score (#PCDATA)>

<!-- WIP: Mouvements -->
<!ELEMENT Move (From, To, PieceMoved, PieceDestroyed, Promotion, Castling, Consequence)>
<!ATTLIST Move chessboard CDATA>
<!ELEMENT From (#PCDATA)>
<!ELEMENT To (#PCDATA)>
<!ELEMENT PieceMoved (#PCDATA)>
<!ELEMENT PieceDestroyed (#PCDATA)>
<!ELEMENT Promotion (#PCDATA)>
<!ELEMENT Castling (#PCDATA)>
<!ELEMENT Consequence (#PCDATA)>

=== jlheig/SER-LAB1/chess.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE Association SYSTEM "chess.dtd">
<Association>
    <Tournament name="Tournoi fédéral d'échecs" winner="bad at chess">
        <Referees>
            <Referee>
                <Name>Dredd</Name>
                <Surname>Judge</Surname>
            </Referee>

            <referee>
                <name>Neymar</name>
                <surname>Jean</surname>
            </referee>
        </Referees>
        <Team name="Chess in Love">
            <Player Sid="1111">
                <Name>John</Name>
                <Surname>Doe</Surname>
                <ELO>1000</ELO>
            </Player>
            <Player Sid="2222">
                <Name>Jane</Name>
                <Surname>Doe</Surname>
                <ELO>1200</ELO>
            </Player>
        </Team>

        <Team name="checkMates">
            <Player Sid="3333">
                <Name>James</Name>
                <Surname>Chess</Surname>
                <ELO>600</ELO>
            </Player>
            <Player Sid="4444">
                <Name>Jessie</Name>
                <Surname>Chess</Surname>
                <ELO>700</ELO>
            </Player>
        </Team>

        <Team name="Chess4ever">
            <Player Sid="5555">
                <Name>Dupont</Name>
                <Surname>Dupont</Surname>
                <ELO>1230</ELO>
            </Player>
            <Player Sid="6666">
                <Name>Dupond</Name>
                <Surname>Dupond</Surname>
                <ELO>1230</ELO>
            </Player>
        </Team>

        <Team name="Bad at chess">
            <Player Sid="7777">
                <Name>Kasparov</Name>
                <Surname>Garry</Surname>
                <ELO>2799</ELO>
            </Player>
            <Player Sid="8888">
                <Name>Carlsen</Name>
                <Surname>Magnus</Surname>
                <ELO>2798</ELO>
            </Player>
        </Team>

        <Match date="2020-03-02" hour="13:15" TeamA="Chess in Love" TeamB="checkMates"
               refereeId="1">
                <Move chessboard="A">
                    <From></From>
                    <To></To>
                    <PieceMoved></PieceMoved>
                    <PieceDestroyed></PieceDestroyed>
                    <Promotion></Promotion>
                    <!-- OU -->
                    <Castling type="kingSide"/>

                    <Consequence type="checkmate/pat/check"/>
                </Move>



            <Score></Score> <!-- Score equipe A -->
            <Score></Score> <!-- Score equipe B -->

        </Match>

        <Match date="2020-03-02" hour="14:20" TeamA="chess4ever" TeamB="bad at chess">
            <Move chessboard="A">
                <From></From>
                <To></To>
                <PieceMoved></PieceMoved>
                <PieceDestroyed></PieceDestroyed>
                <Promotion></Promotion>
                <!-- OU -->
                <Castling type="kingSide"/>

                <Consequence type="checkmate/pat/check"/>
            </Move>



            <Score></Score> <!-- Score equipe A -->
            <Score></Score> <!-- Score equipe B -->

        </Match>

    </Tournament>

    <tournament winner="bad at chess">

        <Team name="Chess in Love">
            <Player Sid="1111">
                <Name>John</Name>
                <Surname>Doe</Surname>
                <ELO>1000</ELO>
            </Player>
            <Player Sid="2222">
                <Name>Jane</Name>
                <Surname>Doe</Surname>
                <ELO>1200</ELO>
            </Player>
        </Team>

        <Team name="checkMates">
            <Player Sid="3333">
                <Name>James</Name>
                <Surname>Chess</Surname>
                <ELO>600</ELO>
            </Player>
            <Player Sid="4444">
                <Name>Jessie</Name>
                <Surname>Chess</Surname>
                <ELO>700</ELO>
            </Player>
        </Team>

        <Team name="Chess4ever">
            <Player Sid="5555">
                <Name>Dupont</Name>
                <Surname>Dupont</Surname>
                <ELO>1230</ELO>
            </Player>
            <Player Sid="6666">
                <Name>Dupond</Name>
                <Surname>Dupond</Surname>
                <ELO>1230</ELO>
            </Player>
        </Team>

        <Team name="Bad at chess">
            <Player Sid="7777">
                <Name>Kasparov</Name>
                <Surname>Garry</Surname>
                <ELO>2799</ELO>
            </Player>
            <Player Sid="8888">
                <Name>Carlsen</Name>
                <Surname>Magnus</Surname>
                <ELO>2798</ELO>
            </Player>
        </Team>

        <Match date="2020-03-02" hour="13:15" TeamA="Chess in Love" TeamB="checkMates">
            <Move chessboard="A">
                <From></From>
                <To></To>
                <PieceMoved></PieceMoved>
                <PieceDestroyed></PieceDestroyed>
                <Promotion></Promotion>
                <!-- OU -->
                <Castling type="kingSide"/>

                <Consequence type="checkmate/pat/check"/>
            </Move>



            <Score></Score> <!-- Score equipe A -->
            <Score></Score> <!-- Score equipe B -->

        </Match>

        <Match date="2020-03-02" hour="14:20" TeamA="chess4ever" TeamB="bad at chess">
            <Move chessboard="A">
                <From></From>
                <To></To>
                <PieceMoved></PieceMoved>
                <PieceDestroyed></PieceDestroyed>
                <Promotion></Promotion>
                <!-- OU -->
                <Castling type="kingSide"/>

                <Consequence type="checkmate/pat/check"/>
            </Move>



            <Score></Score> <!-- Score equipe A -->
            <Score></Score> <!-- Score equipe B -->

        </Match>

    </tournament>

</Association>
